/* Automatically generated by './build/bin/build-entry.js' */

import GenForm from './GenForm/index.js'
import GenButton from './GenButton/index.js'

const components = [GenButton, GenForm]

const install = function (Vue, opts = {}) {
  components.forEach((component) => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  GenButton,
  GenForm,
  install
}
